Task 1: Write a function so that the columns of the output matrix are powers of the input
vector

In [5]:
import numpy as np

In [48]:
def matrix(arr, N, l):
    
    output = np.zeros((len(arr),N))
    for i in range(N):
        output[:,i] = (arr.T)**i
    
    if l:
        return(output)
    else:
        return(output[:,-1::-1])

In [51]:
a = np.array([1,2,3,4])

print(matrix(a,4,1))
print('-'*30)
print(matrix(a,4,0))

[[ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]
 [ 1.  4. 16. 64.]]
------------------------------
[[ 1.  1.  1.  1.]
 [ 8.  4.  2.  1.]
 [27.  9.  3.  1.]
 [64. 16.  4.  1.]]


Task 2 : Write a function to find moving average

In [52]:
import numpy as np

In [53]:
def moving_average(arr, k):
    
    output = []
    n = len(arr)
    for i in range(n-k+1):
        output.append(sum((arr[i:i+k])/k))
        
    return(np.array(output))
    

In [54]:
moving_average(np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]), 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])