# Task 1: 1

In [37]:
import numpy as np


def divide(num1, num2):
    
    try:
        output = num1/num2
    except ZeroDivisionError:
        return num1/np.array(num2)
    except:
        return 'Please enter two numbers!'
    else:
        return output

In [38]:
print(divide(5, 0))
print(divide(5,'a'))

inf
Please enter two numbers!


C:\Users\Vanja\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


# Task 1: 2

In [4]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i, j, k)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2: 1

In [30]:
import numpy as np


def power(x, N, l = True):  # default is True
    
    x = np.array(x)
    matrix = np.zeros((len(x), N))
    for i in range(N):
        matrix[:, i] = x**i
        
    if not l:
        temp = np.zeros((len(x), N))
        for i in range(N):
            temp[:,i] = matrix[:,N-i-1]
        matrix = temp
        
    return matrix


In [35]:
x = [1, 2, 3, 4] 

print(power(x, 3, False), '\n') 
print(power(x, 3, True))

[[ 1.  1.  1.]
 [ 4.  2.  1.]
 [ 9.  3.  1.]
 [16.  4.  1.]] 

[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]]
